require 'erb'

# Generated by Linecook, do not edit.
module Linebook
module Shell
module Bash
def shell_path
  @shell_path ||= '/bin/bash'
end

#################################### su ####################################

# :stopdoc:
SU_LINE = __LINE__ + 2
SU = "self." + ERB.new(<<'END_OF_TEMPLATE', nil, '<>').src
su <%= user %> "<%= capture_path(user, &block) %>"
<% check_status %>

END_OF_TEMPLATE
# :startdoc:

# Switches to a different user for the duration of a block.
# ==== SU ERB
#   su <%= user %> "<%= capture_path(user, &block) %>"
#   <% check_status %>
def su(user=nil, &block)
  eval(SU, binding, __FILE__, SU_LINE)
  nil
end

def _su(*args, &block) # :nodoc:
  capture { su(*args, &block) }
end
end
end
end
