require 'erb'

# Generated by Linecook, do not edit.
module Linebook
module Os
module Ubuntu
############################## addgroup ##############################

# 
def addgroup(name)
  cmd 'addgroup', name
end

def _addgroup(*args, &block) # :nodoc:
  capture { addgroup(*args, &block) }
end

############################### adduser ###############################

# 
def adduser(name)
  cmd 'adduser', name
end

def _adduser(*args, &block) # :nodoc:
  capture { adduser(*args, &block) }
end

############################### package ###############################

# :stopdoc:
PACKAGE_LINE = __LINE__ + 2
PACKAGE = "self." + ERB.new(<<'END_OF_TEMPLATE', nil, '<>').src
apt-get -q install <%= name %><%= blank?(version) ? nil : "=#{version}" %>
<%= check_status %>
END_OF_TEMPLATE
# :startdoc:

# 
# ==== PACKAGE ERB
#   apt-get -q install <%= name %><%= blank?(version) ? nil : "=#{version}" %>
#   <%= check_status %>
def package(name, version=nil)
  eval(PACKAGE, binding, __FILE__, PACKAGE_LINE)
  nil
end

def _package(*args, &block) # :nodoc:
  capture { package(*args, &block) }
end
end
end
end
